### ISSUE TITLE
 运行不起来呢，sync gradle的时候报错

### ISSUE THREAD

**Issue by JokeZhang** [bmfe/android-eros-plugin-simple#1]
`Could not find method implementation() for arguments [com.github.bmfe.eros-nexus:nexus:1.0.1] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.
Open File
`

**Comment by hanliuxin5** [comment]
对，现在这些个代码问题很严重，我晚上修补一下放一个能跑的上来。

**Comment by myliuyx** [comment]
已经修复 可以运行了！
